---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_ssh_user: gavadmin
      ansible_host: 158.160.142.122
      ansible_private_key_file: ~/.ssh/id_ed25519
      ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"

vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_ssh_user: gavadmin
      ansible_host: 158.160.142.122
      ansible_private_key_file: ~/.ssh/id_ed25519
      ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"