---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 51.250.1.252
      ansible_private_key_file: ~/.ssh/id_ed25519
      ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"

vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 51.250.78.242
      ansible_private_key_file: ~/.ssh/id_ed25519
      ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"

lighthouse:
  hosts:
    lighthouse-01:
      ansible_connection: ssh
      ansible_ssh_user: ubuntu
      ansible_host: 51.250.75.189
      ansible_private_key_file: ~/.ssh/id_ed25519
      ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
